## Tarea 4: Agustin Ibarra S.

Un colega le entrega a usted archivos de texto con los resultados de una simulación (simulacion.txt). Este archivo contiene tres columnas separadas por espacios tal que cada fila es un dato y las tres columnas son tres propiedades simuladas de ese dato. 

Escriba una función que lea ese archivo de texto y lo vuelva a guardar en un archivo simulacion.hd5 con tres datasets correspondientes a las tres propiedades de cada dato.

Como usted quiere reutilizar esta función para cualquier otro archivo con tres columnas, la función debe tomar el nombre del archivo de texto y el nombre deseado para el nuevo archivo hd5 como argumentos.

El archivo simulacion.txt contiene por ejemplo lo siguiente:

3.141590000000000094e-03 2.557680595776000416e+02 4.501400409434224770e+01 
6.283180000000000189e-03 3.752818426478838205e+02 2.947770471609068110e+01 
9.424770000000000716e-03 4.246697882492646841e+02 2.843524433400840579e+01 
1.256636000000000038e-02 4.676325636948347437e+02 2.576223788106328882e+01 
1.570795000000000177e-02 4.820912691815412359e+02 1.530261598082400276e+01 
1.884954000000000143e-02 4.337667969674867550e+02 1.450243036000263963e+01 
2.199113000000000109e-02 4.299064323187142804e+02 7.689521175184014012e+00 
2.513272000000000075e-02 3.840742743415148084e+02 5.880658615460115257e+00 
2.827431000000000041e-02 3.464876766126099596e+02 5.062040746246734280e+00 

-----------------------------------------------------------------------------------------------------------------------------

## Desarrollo

Lo que se realizó fue una función que recibe dos nombres, el nombre del archivo txt que poseé datos de solo 3 columnas y el archivo nuevo hd5 que tendrá datasets igual a cada columna. Al primer archivo, en este caso simulacion.txt, se le extraerán los datos y se le colocara en una lista, que poseerá todos los datos, luego se creara el archivo hd5 y se le colocara los datos. Lo importante que estos datos serán las columnas de nuestra lista, cada datasets del archivo hd5 será la columna de la lista. Con esto veremos que se creara el archivo y se verá dentro cada dataset con su dato.

In [3]:
import os 
import numpy as np
import h5py

def hd5(nombre1 , nombre2): 
    '''
    Funcion hd5 la cual recibe archivos .txt con solo tres 
    columnas, para pasarlas a un archivo .hd5 con tres 
    datasets.
    
    Esta funcion es llamada por 2 nombres:
    
    hd5(nombre1, nombre2):
    
    nombre1 = nombre de archivo.txt el cual tiene sus datos
    nombre2 = nombre de su nuevo archivo, ahora en .hd5
    
    '''
    general = [] #Lista que tendrá nuestros datos
    with open(nombre1, 'r') as file: #Abrimos nuestro archivo para poder extraer los datos
        for l in file:
            datos = [] #Aca almacenaremos nuestros datos en listas para asi colocarlas en general
            xin, yin, zin = l.split() 
            datos.append(float(xin))
            datos.append(float(yin))
            datos.append(float(zin))
            general.append(datos) #Con cada uno de estos pasos iremos extrayendo los datos por columna
    general = np.array(general) #Hacemos general un array para asi manejarlo más facil
    f1 = h5py.File(nombre2, "w") #Creamos el archivo .hd5 con el nombre deseado
    a,b = np.array(general).shape #La dimension de general, donde estan los datos
    f1.create_dataset("Propiedad1", (a,1), dtype='f', data=general[:,0])
    f1.create_dataset("Propiedad2", (a,1), dtype='f', data=general[:,1])
    f1.create_dataset("Propiedad3", (a,1), dtype='f', data=general[:,2])#Con cada uno de estos procesos creamos los datasets.
#Destacar que cada dataset lo nombramos por su propiedad.

Veamos si nuestra función esta correcta y crea el archivo;

In [4]:
hd5("simulacion.txt", "simulacion.hdf5")

Ahora entremos en nuestro nuevo archivo creado y veamos si efectivamente están los datos guardados.

In [5]:
f1 = h5py.File('simulacion.hdf5', 'r')
f1.keys()

<KeysViewHDF5 ['Propiedad1', 'Propiedad2', 'Propiedad3']>

Se puede ver que dentro de nuestro archivo están las 3 propiedades de nuestros datos, en este caso 
cada columna. Ahora consigamos lo que tiene cada propiedad y veamos los datos que necesitamos.

In [6]:
p1 = f1.get('Propiedad1')
p2 = f1.get('Propiedad2')
p3 = f1.get('Propiedad3')

In [7]:
p1[:]

array([[0.00314159],
       [0.00628318],
       [0.00942477],
       [0.01256636],
       [0.01570795],
       [0.01884954],
       [0.02199113],
       [0.02513272],
       [0.02827431]], dtype=float32)

In [8]:
p2[:]

array([[255.76807],
       [375.28183],
       [424.6698 ],
       [467.63257],
       [482.09128],
       [433.76678],
       [429.90643],
       [384.07428],
       [346.48767]], dtype=float32)

In [9]:
p3[:]

array([[45.014004 ],
       [29.477705 ],
       [28.435244 ],
       [25.762238 ],
       [15.302616 ],
       [14.50243  ],
       [ 7.6895213],
       [ 5.8806586],
       [ 5.062041 ]], dtype=float32)

Podemos notar que para cada dataset estan sus respectivos datos, por lo que podemos decir que la función 
esta correcta.

# Calificacion: 7.0